"""Utility modules for NewsDigest."""

from newsdigest.utils.http import (
    HTTPClient,
    RateLimiter,
    RetryConfig,
    fetch_url,
    get_shared_client,
)
from newsdigest.utils.text import (
    STOP_WORDS,
    calculate_word_overlap,
    compile_patterns,
    extract_quoted_content,
    find_all_matches,
    fix_punctuation_spacing,
    get_content_words,
    has_excessive_punctuation,
    has_meaningful_content,
    has_numbers,
    has_quote,
    is_all_caps,
    match_any_pattern,
    normalize_whitespace,
    remove_words,
    strip_punctuation,
    word_count,
    word_in_set,
)
from newsdigest.utils.validation import (
    SanitizationError,
    ValidationError,
    is_valid_url,
    sanitize_html,
    sanitize_text,
    validate_article_content,
    validate_article_title,
    validate_enum,
    validate_extraction_mode,
    validate_feed_item_count,
    validate_feed_url,
    validate_positive_int,
    validate_range,
    validate_text_content,
    validate_url,
    validate_url_strict,
)
from newsdigest.utils.logging import (
    LoggedOperation,
    get_logger,
    init_logging,
    log_error,
    log_extraction_complete,
    log_extraction_start,
    log_performance,
    setup_logging,
)
from newsdigest.utils.errors import (
    ErrorContext,
    ErrorReporter,
    ErrorSeverity,
    add_breadcrumb,
    capture_errors,
    capture_exception,
    capture_message,
    configure_error_reporting,
    error_boundary,
    format_exception,
    get_error_context,
    get_error_reporter,
    get_exception_chain,
)

__all__ = [
    # HTTP utilities
    "HTTPClient",
    "RateLimiter",
    "RetryConfig",
    "fetch_url",
    "get_shared_client",
    # Text utilities
    "STOP_WORDS",
    "strip_punctuation",
    "normalize_whitespace",
    "fix_punctuation_spacing",
    "get_content_words",
    "word_count",
    "compile_patterns",
    "match_any_pattern",
    "find_all_matches",
    "word_in_set",
    "has_meaningful_content",
    "calculate_word_overlap",
    "has_quote",
    "has_numbers",
    "is_all_caps",
    "has_excessive_punctuation",
    "extract_quoted_content",
    "remove_words",
    # Validation utilities
    "ValidationError",
    "SanitizationError",
    "validate_url",
    "validate_url_strict",
    "is_valid_url",
    "sanitize_text",
    "sanitize_html",
    "validate_text_content",
    "validate_range",
    "validate_positive_int",
    "validate_enum",
    "validate_extraction_mode",
    "validate_feed_url",
    "validate_feed_item_count",
    "validate_article_content",
    "validate_article_title",
    # Logging utilities
    "setup_logging",
    "get_logger",
    "init_logging",
    "log_performance",
    "LoggedOperation",
    "log_extraction_start",
    "log_extraction_complete",
    "log_error",
    # Error reporting utilities
    "ErrorSeverity",
    "ErrorContext",
    "ErrorReporter",
    "get_error_context",
    "get_error_reporter",
    "configure_error_reporting",
    "capture_exception",
    "capture_message",
    "add_breadcrumb",
    "capture_errors",
    "error_boundary",
    "format_exception",
    "get_exception_chain",
]
